package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/lokiteitor/market-simulator/sdk/models"
)

type OrdersFilter struct {
	Statuses  []models.OrderStatus
	ProductID string
	Side      models.OrderSide
	Since     string
	Limit     int
	Cursor    string
}

// PlaceOrder places a buy or sell order.
func (c *Client) PlaceOrder(ctx context.Context, req models.PlaceOrderRequest) (*models.PlaceOrderResponse, error) {
	var resp models.PlaceOrderResponse
	err := c.do(ctx, http.MethodPost, "/orders", req, &resp, true)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListOrders retrieves a list of orders for the agent, filtered by status, product, side, etc.
func (c *Client) ListOrders(ctx context.Context, filter OrdersFilter) (*models.OrderPage, error) {
	u, err := url.Parse("/orders")
	if err != nil {
		return nil, err
	}
	q := u.Query()
	for _, status := range filter.Statuses {
		q.Add("status", string(status))
	}
	if filter.ProductID != "" {
		q.Set("product_id", filter.ProductID)
	}
	if filter.Side != "" {
		q.Set("side", string(filter.Side))
	}
	if filter.Since != "" {
		q.Set("since", filter.Since)
	}
	if filter.Limit > 0 {
		q.Set("limit", strconv.Itoa(filter.Limit))
	}
	if filter.Cursor != "" {
		q.Set("cursor", filter.Cursor)
	}
	u.RawQuery = q.Encode()

	var resp models.OrderPage
	err = c.do(ctx, http.MethodGet, u.String(), nil, &resp, true)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetOrder retrieves a detailed view of a specific order.
func (c *Client) GetOrder(ctx context.Context, orderID string) (*models.Order, error) {
	var resp models.Order
	err := c.do(ctx, http.MethodGet, fmt.Sprintf("/orders/%s", orderID), nil, &resp, true)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// CancelOrder cancels an active or partially completed order.
// Returns the order if it was already in a terminal state (HTTP 200), otherwise nil (HTTP 204).
func (c *Client) CancelOrder(ctx context.Context, orderID string) (*models.Order, error) {
	var resp models.Order
	// We use the raw request to distinguish 200 vs 204 in client.go, or we can handle it directly.
	// Since client.do only returns an error if not 2xx, we can check if response was populated.
	err := c.do(ctx, http.MethodDelete, fmt.Sprintf("/orders/%s", orderID), nil, &resp, true)
	if err != nil {
		return nil, err
	}
	if resp.OrderID == "" {
		return nil, nil // 204 No Content
	}
	return &resp, nil
}

// GetOrderTrades retrieves trades generated by a specific order.
func (c *Client) GetOrderTrades(ctx context.Context, orderID string) ([]models.Trade, error) {
	var resp []models.Trade
	err := c.do(ctx, http.MethodGet, fmt.Sprintf("/orders/%s/trades", orderID), nil, &resp, true)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
